import { ebcToHex, srmToHex } from './index.js'
import type { ColorOptions } from './index.js'

/**
 * Strict numeric parse. Rejects empty strings, NaN, Infinity, and trailing
 * garbage ("20px" → null, unlike parseFloat which would return 20).
 * @returns the parsed number, or null if invalid.
 */
export function parseNumber(raw: string | undefined): number | null {
  if (raw === undefined || raw.trim() === '') return null
  const n = Number(raw)
  return Number.isFinite(n) ? n : null
}

/**
 * Parses a "min-max" range. Requires exactly two finite parts with min <= max.
 * @throws RangeError on malformed input (negative leading dash, extra dashes, non-numeric).
 */
export function parseRange(raw: string | undefined, unit: string): [number, number] {
  if (!raw) return unit === 'srm' ? [1, 40] : [1, 80]
  const parts = raw.split('-')
  const a = parts.length === 2 ? parseNumber(parts[0]) : null
  const b = parts.length === 2 ? parseNumber(parts[1]) : null
  if (a === null || b === null || a > b) {
    throw new RangeError(`Invalid range: ${raw}. Expected format min-max (e.g. 1-80).`)
  }
  return [a, b]
}

function hexFn(unit: string): (v: number, o?: ColorOptions) => string {
  return unit === 'srm' ? srmToHex : ebcToHex
}

/** Builds a CSS stylesheet of color/background utility classes for the value range. */
export function generateCss(min: number, max: number, unit: string, options: ColorOptions): string {
  const toHex = hexFn(unit)
  const prefix = unit === 'srm' ? 'srm' : 'ebc'
  const lines = [`/* ${unit.toUpperCase()} beer color classes — generated by beer-color-rgb (A.J. de Lange spectral model) */`]
  for (let val = min; val <= max; val++) {
    const hex = toHex(val, options)
    lines.push(`.${prefix}-${val} { color: ${hex}; }`)
    lines.push(`.${prefix}-bg-${val} { background-color: ${hex}; }`)
  }
  return lines.join('\n') + '\n'
}

/** Builds a JSON map of value → hex for the value range. */
export function generateJson(min: number, max: number, unit: string, options: ColorOptions): string {
  const toHex = hexFn(unit)
  const map: Record<number, string> = {}
  for (let val = min; val <= max; val++) map[val] = toHex(val, options)
  return JSON.stringify(map, null, 2) + '\n'
}
